language: node_js
node_js:
- '10'
branches:
  only:
  - master
jobs:
  include:
  - before_script:
    - npm install
    - export ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE=$TRAVIS_COMMIT_$(date +%Y_%m_%d_%H_%M_%S).zip
    - export ELASTIC_BEANSTALK_DESCRIPTION=$TRAVIS_COMMIT_MESSAGE && echo $ELASTIC_BEANSTALK_DESCRIPTION
    - export ELASTIC_BEANSTALK_LABEL=$TRAVIS_BRANCH-$TRAVIS_COMMIT && echo $ELASTIC_BEANSTALK_LABEL
    script:
    - npm run build
    - zip -r $ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE . -x '*.git*' -q
    deploy:
    - provider: elasticbeanstalk
      access_key_id: "$AWS_ACCESS_KEY_ID_FOR_DEPLOYMENT"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY_FOR_DEPLOYMENT"
      region: ap-southeast-1
      zip_file: "$ELASTICBEANSTALK_DEPLOYMENT_ZIP_FILE"
      app: vaultgovsg-send
      env: send-vaultgovsg-staging
      bucket_name: send-vaultgovsg-staging-elasticbeanstalk
      edge: true
      wait_until_deployed: true
      on:
        branch: master
notifications:
  slack:
    secure: CBQ2FkCAeL+Lh/noPDGiNyn8wtsCvPPKo4Q8brQzd4xDOGlr9gy6LRWkioD6UGq4PPrZGmVfeRWFkljA6nLy5lCiftD2Er8vC+qtg13kLFmK+Ng/rn9a/XUxfxtvqxBtvF2wsYSVfrVQYQCAKiPzvPL8941pODYAS1DtXwdJ0Sdja/CX+Llss5+w9RzRVDQ/uP+t35HmqRKObvjYc2ket2pNEtcw97hmnRl1PukiyBAU3B3NugEOYcf7Iz7y66+zX0FwnApW2EE677OeksBPl+eWcQr6Y8ZFpp5QW1Lo9YcpFeJZg4hbQoMh4juQoUX459ID3jIrV8HFmxyX6egaggqlyts6HAacJChn0KIj8jcmnzQU1h1/rhj2bZ+b/tH+U8iGwfTrf3W3lQo9su8KOZQagxrwV/PUW9rqOYURUacC7S8R4enqrDeOqEKUd1Qg0SSdAzgeNkOVYHGrkcBPvktgEUnqm/aCz61Nc+FQ/WTgq23dI0M2LlUM+qP86zczC3a4Ajex2AKgTmQRVR4BZtn60dGnuOVkxVxT5DynlvfU/gvCST8s3rs7Ifgatt8AY4j8NiQC6wIVtH35Zhb+w99yhDAN/htqBNPb4PtHACYkQJX8h/YGpIL45OhPknyBisLgcyrWJ5VhXie5vQeTWeS7B6ObZBsXnl9tT9p/Wlw=
