const convict = require('convict');
const { tmpdir } = require('os');
const path = require('path');
const { randomBytes } = require('crypto');

const conf = convict({
  LOGIN_URL: {
    format: String,
    default: 'http://localhost:1443',
    env: 'LOGIN_URL'
  },
  SEND_FRONTEND_REDIRECT_KEY: {
    format: String,
    default: 'send',
    env: 'SEND_FRONTEND_REDIRECT_KEY'
  },
  s3_bucket: {
    format: String,
    default: 'secret-storage-test.vault.gov.sg',
    env: 'S3_BUCKET'
  },
  gcs_bucket: {
    format: String,
    default: '',
    env: 'GCS_BUCKET'
  },
  expire_times_seconds: {
    format: Array,
    default: [300, 3600, 86400, 604800],
    env: 'EXPIRE_TIMES_SECONDS'
  },
  default_expire_seconds: {
    format: Number,
    default: 86400,
    env: 'DEFAULT_EXPIRE_SECONDS'
  },
  max_expire_seconds: {
    format: Number,
    default: 86400 * 7,
    env: 'MAX_EXPIRE_SECONDS'
  },
  anon_max_expire_seconds: {
    format: Number,
    default: 86400 * 7,
    env: 'ANON_MAX_EXPIRE_SECONDS'
  },
  download_counts: {
    format: Array,
    default: [1, 2, 3, 4, 5, 20, 50, 100],
    env: 'DOWNLOAD_COUNTS'
  },
  max_downloads: {
    format: Number,
    default: 100,
    env: 'MAX_DOWNLOADS'
  },
  anon_max_downloads: {
    format: Number,
    default: 100,
    env: 'ANON_MAX_DOWNLOADS'
  },
  max_files_per_archive: {
    format: Number,
    default: 64,
    env: 'MAX_FILES_PER_ARCHIVE'
  },
  max_archives_per_user: {
    format: Number,
    default: 16,
    env: 'MAX_ARCHIVES_PER_USER'
  },
  allowed_file_types: {
    format: Array,
    default: [
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
      'application/vnd.ms-word.document.macroEnabled.12',
      'application/vnd.ms-word.template.macroenabled.12',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
      'application/vnd.ms-excel.sheet.macroenabled.12',
      'application/vnd.ms-excel.template.macroenabled.12',
      'application/vnd.ms-excel.addin.macroenabled.12',
      'application/vnd.ms-excel.sheet.binary.macroenabled.12',
      'application/vnd.ms-powerpoint',
      'application/vnd.ms-powerpoint.addin.macroenabled.12',
      'application/vnd.ms-powerpoint.presentation.macroenabled.12',
      'application/vnd.ms-powerpoint.template.macroenabled.12',
      'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'audio/1d-interleaved-parityfec',
      'audio/32kadpcm',
      'audio/3gpp',
      'audio/3gpp2',
      'audio/aac',
      'audio/ac3',
      'audio/AMR',
      'audio/AMR-WB',
      'audio/amr-wb+',
      'audio/aptx',
      'audio/asc',
      'audio/ATRAC-ADVANCED-LOSSLESS',
      'audio/ATRAC-X',
      'audio/ATRAC3',
      'audio/basic',
      'audio/BV16',
      'audio/BV32',
      'audio/clearmode',
      'audio/CN',
      'audio/DAT12',
      'audio/dls',
      'audio/dsr-es201108',
      'audio/dsr-es202050',
      'audio/dsr-es202211',
      'audio/dsr-es202212',
      'audio/DV',
      'audio/DVI4',
      'audio/eac3',
      'audio/encaprtp',
      'audio/EVRC',
      'audio/EVRC-QCP',
      'audio/EVRC0',
      'audio/EVRC1',
      'audio/EVRCB',
      'audio/EVRCB0',
      'audio/EVRCB1',
      'audio/EVRCNW',
      'audio/EVRCNW0',
      'audio/EVRCNW1',
      'audio/EVRCWB',
      'audio/EVRCWB0',
      'audio/EVRCWB1',
      'audio/EVS',
      'audio/example',
      'audio/flexfec',
      'audio/fwdred',
      'audio/G711-0',
      'audio/G719',
      'audio/G7221',
      'audio/G722',
      'audio/G723',
      'audio/G726-16',
      'audio/G726-24',
      'audio/G726-32',
      'audio/G726-40',
      'audio/G728',
      'audio/G729',
      'audio/G729D',
      'audio/G729E',
      'audio/GSM',
      'audio/GSM-EFR',
      'audio/GSM-HR-08',
      'audio/iLBC',
      'audio/ip-mr_v2.5',
      'audio/L8',
      'audio/L16',
      'audio/L20',
      'audio/L24',
      'audio/LPC',
      'audio/MELP',
      'audio/MELP600',
      'audio/MELP1200',
      'audio/MELP2400',
      'audio/mhas',
      'audio/mobile-xmf',
      'audio/MPA',
      'audio/mp4',
      'audio/MP4A-LATM',
      'audio/mpa-robust',
      'audio/mpeg',
      'audio/mpeg4-generic',
      'audio/ogg',
      'audio/opus',
      'audio/PCMA',
      'audio/PCMA-WB',
      'audio/PCMU',
      'audio/PCMU-WB',
      'audio/prs.sid',
      'audio/raptorfec',
      'audio/RED',
      'audio/rtp-enc-aescm128',
      'audio/rtploopback',
      'audio/rtp-midi',
      'audio/rtx',
      'audio/SMV',
      'audio/SMV0',
      'audio/SMV-QCP',
      'audio/sp-midi',
      'audio/speex',
      'audio/t140c',
      'audio/t38',
      'audio/telephone-event',
      'audio/TETRA_ACELP',
      'audio/TETRA_ACELP_BB',
      'audio/tone',
      'audio/UEMCLIP',
      'audio/ulpfec',
      'audio/usac',
      'audio/VDVI',
      'audio/VMR-WB',
      'audio/vnd.3gpp.iufp',
      'audio/vnd.4SB',
      'audio/vnd.audiokoz',
      'audio/vnd.CELP',
      'audio/vnd.cisco.nse',
      'audio/vnd.cmles.radio-events',
      'audio/vnd.cns.anp1',
      'audio/vnd.cns.inf1',
      'audio/vnd.dece.audio',
      'audio/vnd.digital-winds',
      'audio/vnd.dlna.adts',
      'audio/vnd.dolby.heaac.1',
      'audio/vnd.dolby.heaac.2',
      'audio/vnd.dolby.mlp',
      'audio/vnd.dolby.mps',
      'audio/vnd.dolby.pl2',
      'audio/vnd.dolby.pl2x',
      'audio/vnd.dolby.pl2z',
      'audio/vnd.dolby.pulse.1',
      'audio/vnd.dra',
      'audio/vnd.dts',
      'audio/vnd.dts.hd',
      'audio/vnd.dts.uhd',
      'audio/vnd.dvb.file',
      'audio/vnd.everad.plj',
      'audio/vnd.hns.audio',
      'audio/vnd.lucent.voice',
      'audio/vnd.ms-playready.media.pya',
      'audio/vnd.nokia.mobile-xmf',
      'audio/vnd.nortel.vbk',
      'audio/vnd.nuera.ecelp4800',
      'audio/vnd.nuera.ecelp7470',
      'audio/vnd.nuera.ecelp9600',
      'audio/vnd.octel.sbc',
      'audio/vnd.presonus.multitrack',
      'audio/vnd.qcelp',
      'audio/vnd.rhetorex.32kadpcm',
      'audio/vnd.rip',
      'audio/vnd.sealedmedia.softseal.mpeg',
      'audio/vnd.vmx.cvsd',
      'audio/vorbis',
      'audio/vorbis-config',
      'image/gif',
      'image/jpeg',
      'image/bmp',
      'image/png',
      'text/csv',
      'text/plain',
      'video/1d-interleaved-parityfec',
      'video/3gpp',
      'video/3gpp2',
      'video/3gpp-tt',
      'video/BMPEG',
      'video/BT656',
      'video/CelB',
      'video/DV',
      'video/encaprtp',
      'video/example',
      'video/flexfec',
      'video/H261',
      'video/H263',
      'video/H263-1998',
      'video/H263-2000',
      'video/H264',
      'video/H264-RCDO',
      'video/H264-SVC',
      'video/H265',
      'video/iso.segment',
      'video/JPEG',
      'video/jpeg2000',
      'video/mj2',
      'video/MP1S',
      'video/MP2P',
      'video/MP2T',
      'video/mp4',
      'video/MP4V-ES',
      'video/MPV',
      'video/mpeg4-generic',
      'video/nv',
      'video/ogg',
      'video/pointer',
      'video/quicktime',
      'video/raptorfec',
      'video/rtp-enc-aescm128',
      'video/rtploopback',
      'video/rtx',
      'video/smpte291',
      'video/SMPTE292M',
      'video/ulpfec',
      'video/vc1',
      'video/vc2',
      'video/vnd.CCTV',
      'video/vnd.dece.hd',
      'video/vnd.dece.mobile',
      'video/vnd.dece.mp4',
      'video/vnd.dece.pd',
      'video/vnd.dece.sd',
      'video/vnd.dece.video',
      'video/vnd.directv.mpeg',
      'video/vnd.directv.mpeg-tts',
      'video/vnd.dlna.mpeg-tts',
      'video/vnd.dvb.file',
      'video/vnd.fvt',
      'video/vnd.hns.video',
      'video/vnd.iptvforum.1dparityfec-1010',
      'video/vnd.iptvforum.1dparityfec-2005',
      'video/vnd.iptvforum.2dparityfec-1010',
      'video/vnd.iptvforum.2dparityfec-2005',
      'video/vnd.iptvforum.ttsavc',
      'video/vnd.iptvforum.ttsmpeg2',
      'video/vnd.motorola.video',
      'video/vnd.motorola.videop',
      'video/vnd.mpegurl',
      'video/vnd.ms-playready.media.pyv',
      'video/vnd.nokia.interleaved-multimedia',
      'video/vnd.nokia.mp4vr',
      'video/vnd.nokia.videovoip',
      'video/vnd.objectvideo',
      'video/vnd.radgamettools.bink',
      'video/vnd.radgamettools.smacker',
      'video/vnd.sealed.mpeg1',
      'video/vnd.sealed.mpeg4',
      'video/vnd.sealed.swf',
      'video/vnd.sealedmedia.softseal.mov',
      'video/vnd.uvvu.mp4',
      'video/vnd.youtube.yt',
      'video/vnd.vivo',
      'video/VP8'
    ],
    env: 'ALLOWED_FILE_TYPES'
  },
  redis_host: {
    format: String,
    default: 'localhost',
    env: 'REDIS_HOST'
  },
  redis_event_expire: {
    format: Boolean,
    default: false,
    env: 'REDIS_EVENT_EXPIRE'
  },
  listen_address: {
    format: 'ipaddress',
    default: '0.0.0.0',
    env: 'IP_ADDRESS'
  },
  listen_port: {
    format: 'port',
    default: 1443,
    arg: 'port',
    env: 'PORT'
  },
  logging_url: {
    format: String,
    default: 'http://localhost:4000/secret_datasets',
    env: 'LOGGING_URL'
  },
  analytics_id: {
    format: String,
    default: '',
    env: 'GOOGLE_ANALYTICS_ID'
  },
  sentry_id: {
    format: String,
    default: '',
    env: 'SENTRY_CLIENT'
  },
  sentry_dsn: {
    format: String,
    default: '',
    env: 'SENTRY_DSN'
  },
  env: {
    format: ['production', 'development', 'test'],
    default: 'development',
    env: 'NODE_ENV'
  },
  max_file_size: {
    format: Number,
    default: 10 * 1024 * 1024 * 1024,
    env: 'MAX_FILE_SIZE'
  },
  anon_max_file_size: {
    format: Number,
    default: 10 * 1024 * 1024 * 1024,
    env: 'ANON_MAX_FILE_SIZE'
  },
  l10n_dev: {
    format: Boolean,
    default: false,
    env: 'L10N_DEV'
  },
  base_url: {
    format: 'url',
    default: 'https://send.firefox.com',
    env: 'BASE_URL'
  },
  file_dir: {
    format: 'String',
    default: `${tmpdir()}${path.sep}send-${randomBytes(4).toString('hex')}`,
    env: 'FILE_DIR'
  },
  fxa_url: {
    format: 'url',
    default: 'https://send-fxa.dev.lcip.org',
    env: 'FXA_URL'
  },
  fxa_client_id: {
    format: String,
    default: '', // disabled
    env: 'FXA_CLIENT_ID'
  },
  fxa_key_scope: {
    format: String,
    default: 'https://identity.mozilla.com/apps/send',
    env: 'FXA_KEY_SCOPE'
  },
  survey_url: {
    format: String,
    default: '',
    env: 'SURVEY_URL'
  },
  ip_db: {
    format: String,
    default: '',
    env: 'IP_DB'
  },
  cookie_secret: {
    format: String,
    default: '',
    env: 'COOKIE_SECRET'
  },
  cookie_domain: {
    format: String,
    default: '',
    env: 'COOKIE_DOMAIN'
  },
  redis_session_url: {
    format: String,
    default: '',
    env: 'REDIS_SESSION_URL'
  }
});

// Perform validation
conf.validate({ allowed: 'strict' });

const props = conf.getProperties();
module.exports = props;
